### ISSUE TITLE
Error: No route to host: /169.254.169.254:80

### ISSUE THREAD

**Issue by GuilhermeVitorino** [dario-vega/demo-graphql-nosql-spring#2]
Hello Dario,

I'm trying to run this application and I'm getting the following error:

Caused by: java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /169.254.169.254:80

Could you help me with this issue?

**Comment by dario-vega** [comment]
Oi Guilherme,

Sure I can help you.

When doing the connection, which OCI region are you trying to reach? I am trying to understand the IP address 169.254.169.254, and I cannot find the OCI Region you are trying to get. 

Can you please provide me with the instructions you are using to make the connection?

In my case, I am trying to reach Ashburn, so I am executing
```
export OCI_REGION="us-ashburn-1"
export OCI_NOSQL_COMPID="ocid1.compartment.oc1..xxxx"
./mvnw clean spring-boot:run
```

In this version, I am using instance principals, so the application must be run from an OCI instance (VM) having access to the Oracle NoSQL Cloud service (via Internet Gateway or Service Gateway)

**Comment by dario-vega** [comment]
BTW, If you need support for on-premise, CloudSim, or other connections mode to OCI; Let me know, it is easy to implement. A few minutes to change and test the connection 

e.g on-premise non-secure (including kvlite) use the branch `on-premise` (https://github.com/dario-vega/demo-graphql-nosql-spring/tree/on-premise)

`git clone https://github.com/dario-vega/demo-graphql-nosql-spring.git --branch on-premise`

**Comment by GuilhermeVitorino** [comment]
Hi Dario,

I did it work!

Yes, I was trying to run locally (on-premise).

I used SignatureProvider instead of Instance Principal. See my config class below:

```
@Bean
public NosqlDbConfig nosqlDbConfig() throws java.io.IOException {
    File privateKey = ResourceUtils.getFile("classpath:svc_m2g_nosql_key.pem");
    NoSQLHandleConfig noSQLHandleConfig = new NoSQLHandleConfig(

            new SignatureProvider(
                    "ocid1.tenancy.oc1..aaa...",  //tenantId
                    "ocid1.user.oc1..aaa...",  //userId
                    "94:10:42:...",  // fingerprint of the key
                    privateKey,
                    null, // passphrase for the (encrypted) private key
                    Region.SA_SAOPAULO_1
            )
    );

    noSQLHandleConfig.setDefaultCompartment("ocid1.compartment.oc1..aaa...");

    return new NosqlDbConfig(noSQLHandleConfig);
}
```

**Comment by dario-vega** [comment]
Great, I will close this issue. Feedback is welcome. As you can see, it is still under construction. It is supposed to be a Tutorial, so I tried to show a simple use case (reusing existing spring tutorials). You can also use it for on-premises, as shown above - branch on-premise.

Muito Obrigado,

Dario
If you want, maybe you can join our **DevRel slack workspace** http://bit.ly/odevrel-slack, and we can discuss it. In this public slack workspace, you can find a slack channel dedicated called `oracle-nosql` and more (there is also a channel `desenvolvedores-brasil` and `desarrolladores-latinoamerica`)  or you can send me a direct message (Dario VEGA).
